---
- name: install cfssl | Debug show pakage to install
  debug:
    msg: download from {{ item.url }} to {{ item.path }}
  with_items: "{{ download_list }}"

- name: install cfssl | Download pakage
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.path }}"
    checksum: "{{ item.checksum }}"
    mode: '0550'
  with_items: "{{ download_list }}"
