---
- name: install cfssl | Download pakage neaded 
  debug:
    msg: download from {{ item.url }} to {{ item.path }}
  with_items: "{{ download_list }}"

- name: install cfssl | Download pakage
  get_url:
    url: "{{ item.url }}"
    dest:  "{{ item.path }}"
    checksum: "{{ item.checksum }}"
    mode: '0550'
  with_items: "{{ download_list }}"
  delegate_to: "{{ keyring_host }}"

- name: install cfssl | Create directory tree on "{{ keyring_host }}"
  file:
    state: directory
    dest: "{{ item }}"
  with_items: "{{ dir_list }}"
  delegate_to: "{{ keyring_host }}"

- name: install cfssl | Create directory tree on nodes
  file:
    state: directory
    dest: "{{ item }}"
  with_items: "{{ create_node_list }}"

- name: install cfssl | Create certificate dir
  file:
    state: directory
    dest: "{{ item.value.path }}"
  with_items: "{{ certificate_directive | dict2items }}"
  delegate_to: "{{ keyring_host }}"

- name: install cfssl | Create directory tree
  debug:
    var: item
  with_items: "{{ certificate_directive | dict2items }}"
  delegate_to: "{{ keyring_host }}"

- name: install cfssl | Create cfssl configurations
  copy:
    content: "{{ item.value.configuration | to_nice_json }}"
    dest: "{{ item.value.configurations_path }}"
  with_items: "{{ certificate_directive | dict2items }}"
  delegate_to: "{{ keyring_host }}"

- name: install cfssl | Create certificate dir
  file:
    state: directory
    dest: "{{ node_certificate.path }}"
  delegate_to: "{{ keyring_host }}"

- name: debug
  debug:
    var: node_certificate.configuration
  delegate_to: "{{ keyring_host }}"

- name: install cfssl | Create cfssl Node
  copy:
    content: "{{ node_certificate.configuration | to_nice_json }}"
    dest: "{{ node_certificate.configurations_path }}"
  delegate_to: "{{ keyring_host }}"
