---
- name: main | install cfssl in host
  import_tasks: install_cfssl.yml

- name: main | create configurations file
  import_tasks: conf.yml

- name: main | import create certs
  import_tasks: create_cert.yml

- name: main | import create certs
  import_tasks: install_certificate.yaml