---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: node-1
    groups:
      - elk
  - name: node-2
    groups:
      - elk
  - name: node-3
    groups:
      - elk
  - name: keyring
    groups:
      - keyring
provisioner:
  name: ansible
  options:
    diff: True
    v: True
  playbooks:
    create: create.yml
    prepare: prepare.yml
    destroy: destroy.yml
scenario:
  name: default
verifier:
  name: goss
