---

- name: just install cfssl
  hosts: install
  gather_facts: true
  roles:
    - role: ansible-cfssl
      install: True
      configure: False

- name: install and configure
  hosts: configure
  gather_facts: true
  roles:
    - role: ansible-cfssl
      install: True
      configure: False
